apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dummy-project
  namespace: argocd
spec:
  description: Dummy project running dummy_server
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: ''
    kind: '*'
